"""Changes roles schema

Revision ID: 257e04c2d827
Revises: 085b3322689b
Create Date: 2020-04-30 11:40:49.145145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257e04c2d827'
down_revision = '085b3322689b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
